# Generated by Django 3.1.7 on 2021-04-30 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_cart_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, unique=True, verbose_name="Фамілія/Ім'я")),
                ('phone', models.IntegerField(max_length=100, verbose_name='Номер телефону')),
                ('quantity', models.IntegerField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
            options={
                'db_table': 'Order',
                'ordering': ['date_added'],
            },
        ),
    ]
