# Generated by Django 3.1.7 on 2021-05-10 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(blank=True, choices=[('готівка', 'Готівка'), ('на карточку', 'На карточку')], max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='region',
            field=models.CharField(choices=[('тернопільська область', 'Тернопільська область'), ('львівська область', 'Львівська область'), ('волиська область', 'Волинська область'), ('рівненська область', 'Рівненська область')], default='львівська область', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping',
            field=models.CharField(choices=[('самовивіз', 'Самовивіз'), ('укрпошта', 'Укрпошта'), ('нова пошта', 'Нова пошта')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.TextField(max_length=20, verbose_name='Номер телефону'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_name',
            field=models.CharField(max_length=100, verbose_name="Фамілія/Ім'я"),
        ),
    ]
