# Generated by Django 3.1.7 on 2021-05-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20210510_2256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['date_added'], 'verbose_name': 'order', 'verbose_name_plural': 'order'},
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(blank=True, choices=[('на карточку', 'На карточку'), ('готівка', 'Готівка')], max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='region',
            field=models.CharField(choices=[('волиська область', 'Волинська область'), ('львівська область', 'Львівська область'), ('рівненська область', 'Рівненська область'), ('тернопільська область', 'Тернопільська область')], default='львівська область', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping',
            field=models.CharField(choices=[('нова пошта', 'Нова пошта'), ('укрпошта', 'Укрпошта'), ('самовивіз', 'Самовивіз')], default=None, max_length=50),
        ),
    ]
