# Generated by Django 3.1.7 on 2021-05-13 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20210513_2020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'order', 'verbose_name_plural': 'order'},
        ),
        migrations.AlterField(
            model_name='order',
            name='region',
            field=models.CharField(choices=[('тернопільська область', 'Тернопільська область'), ('львівська область', 'Львівська область'), ('рівненська область', 'Рівненська область'), ('волиська область', 'Волинська область')], default='львівська область', max_length=100),
        ),
        migrations.AlterModelTable(
            name='order',
            table=None,
        ),
    ]
