# Generated by Django 3.1.7 on 2021-05-13 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20210513_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='region',
            field=models.CharField(choices=[('волиська область', 'Волинська область'), ('рівненська область', 'Рівненська область'), ('львівська область', 'Львівська область'), ('тернопільська область', 'Тернопільська область')], default='львівська область', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping',
            field=models.CharField(choices=[('самовивіз', 'Самовивіз'), ('нова пошта', 'Нова пошта'), ('укрпошта', 'Укрпошта')], default=None, max_length=50),
        ),
    ]
